services:
  minio-dev:
    container_name: minio-dev
    image: minio/minio:RELEASE.2022-11-08T05-27-07Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio-dev
    entrypoint: >
      sh -c "
      sleep 10 &&
      mc config host add myminio http://minio-dev:9000 minioadmin minioadmin &&
      mc mb myminio/ufc || echo 'Bucket already exists'
      "

  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    depends_on:
      - minio-dev

volumes:
  minio_data: