services:
  minio-dev:
    container_name: minio-dev
    image: minio/minio:RELEASE.2022-11-08T05-27-07Z
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9001:9000"
      - "9002:9001"
    volumes:
      - minio_data:/data

  minio-init:
    image: minio/mc
    depends_on:
      - minio-dev
    entrypoint: >
      sh -c "
      sleep 10 &&
      mc config host add myminio http://minio-dev:9000 minioadmin minioadmin &&
      mc mb myminio/ufc || echo 'Bucket already exists'
      "
  
  postgres_db:
      container_name: postgres_db
      image: postgres:12
      environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
          - POSTGRES_DB=ufc_db
          - POSTGRES_PORT=5432
      ports:
          - "5432:5432"
      depends_on:
        - minio-dev
    

  app:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    command: tail -f /dev/null
    stdin_open: true
    tty: true
    depends_on:
      - minio-dev

volumes:
  minio_data: